export const ResourceKey = {
    TITLE: "TITLE",

    POSITIONS: "POSITIONS",
    P_SERVICE: "P_SERVICE",
    P_SERVICE_POSITIONS_LIBERO: "P_SERVICE_POSITIONS_LIBERO",
    P_ATTACK: "P_ATTACK",
    P_DEFENSE: "P_DEFENSE",
    P_GAME_POSITIONS_LIBERO: "P_GAME_POSITIONS_LIBERO",

    ATTACK_ACTION: "ATTACK_ACTION",
    A_ORIGINAL: "A_ORIGINAL",
    A_OUTSIDE: "A_OUTSIDE",
    A_MIDDLE: "A_MIDDLE",
    A_OPPOSITE: "A_OPPOSITE",

    DEFENSE_ACTION: "DEFENSE_ACTION",
    D_ORIGINAL: "D_ORIGINAL",
    D_RELANCE: "D_RELANCE",
    D_OUTSIDE: "D_OUTSIDE",
    D_MIDDLE: "D_MIDDLE",
    D_OPPOSITE: "D_OPPOSITE",

    GAME_POSITION: "GAME_POSITION",
    GP_FRONT: "GP_FRONT",
    GP_BACK: "GP_BACK",

    ROLE: "ROLE",
    ROLE_SETTER: "ROLE_SETTER",
    ROLE_OPPOSITE: "ROLE_OPPOSITE",
    ROLE_OUTSIDE_A: "ROLE_OUTSIDE_A",
    ROLE_OUTSIDE_B: "ROLE_OUTSIDE_B",
    ROLE_MIDDLE_A: "ROLE_MIDDLE_A",
    ROLE_MIDDLE_B: "ROLE_MIDDLE_B",
    ROLE_LIBERO: "ROLE_LIBERO",

    SERVICE_ACTION: "SERVICE_ACTION",
    SA_ORIGINAL: "SA_ORIGINAL",
    SA_SERVING: "SA_SERVING",
    SA_RECEIVING: "SA_RECEIVING",

    SERVICE_POSITION: "SERVICE_POSITION",
    SP_P1: "SP_P1",
    SP_P6: "SP_P6",
    SP_P5: "SP_P5",
    SP_P4: "SP_P4",
    SP_P3: "SP_P3",
    SP_P2: "SP_P2",

    LEGENDE: "LEGENDE",
    DOWNLOAD: "DOWNLOAD",

    LIBERO_WITH:"LIBERO_WITH",
    LIBERO_WITHOUT:"LIBERO_WITHOUT",
};