export const ResourceKey = {
    TITLE: "TITLE",

    POSITIONS: "POSITIONS",
    P_SERVICE: "P_SERVICE",
    P_SERVICE_POSITIONS_LIBERO: "P_SERVICE_POSITIONS_LIBERO",
    P_GAME: "P_GAME",
    P_GAME_POSITIONS_LIBERO: "P_GAME_POSITIONS_LIBERO",

    GAME_ACTION: "GAME_ACTION",
    GA_ORIGINAL: "GA_ORIGINAL",
    GA_RELANCE: "GA_RELANCE",
    GA_ATTACK_OUTSIDE: "GA_ATTACK_OUTSIDE",
    GA_ATTACK_MIDDLE: "GA_ATTACK_MIDDLE",
    GA_ATTACK_OPPOSITE: "GA_ATTACK_OPPOSITE",
    GA_DEFENSE_OUTSIDE: "GA_DEFENSE_OUTSIDE",
    GA_DEFENSE_MIDDLE: "GA_DEFENSE_MIDDLE",
    GA_DEFENSE_OPPOSITE: "GA_DEFENSE_OPPOSITE",

    GAME_POSITION: "GAME_POSITION",
    GP_FRONT: "GP_FRONT",
    GP_BACK: "GP_BACK",

    ROLE: "ROLE",
    ROLE_SETTER: "ROLE_SETTER",
    ROLE_OPPOSITE: "ROLE_OPPOSITE",
    ROLE_OUTSIDE_A: "ROLE_OUTSIDE_A",
    ROLE_OUTSIDE_B: "ROLE_OUTSIDE_B",
    ROLE_MIDDLE_A: "ROLE_MIDDLE_A",
    ROLE_MIDDLE_B: "ROLE_MIDDLE_B",
    ROLE_LIBERO: "ROLE_LIBERO",

    SERVICE_ACTION: "SERVICE_ACTION",
    SA_ORIGINAL: "SA_ORIGINAL",
    SA_SERVING: "SA_SERVING",
    SA_RECEIVING: "SA_RECEIVING",

    SERVICE_POSITION: "SERVICE_POSITION",
    SP_P1: "SP_P1",
    SP_P6: "SP_P6",
    SP_P5: "SP_P5",
    SP_P4: "SP_P4",
    SP_P3: "SP_P3",
    SP_P2: "SP_P2",

    LEGENDE: "LEGENDE",
    DOWNLOAD: "DOWNLOAD",

    LIBERO_WITH:"LIBERO_WITH",
    LIBERO_WITHOUT:"LIBERO_WITHOUT",
};